//Drone Conifg file. autogenerated at Sat Feb 29 23:00:12 EET 2020
#define FRAME_SIZE_OF_DRONE 410
#define LIS3DH_ACCELEROMETER 1 	
#define BMP180_BAROMETER 1
#define MPU6050_GYRO 1
#define MOTOR_SIZE 2212_1600
#define PROPELLER_SIZE 4045R
#define DRONE_NAME DroneTestExample
#define AUTO_LEVEL_MODE true
#define BARO_SUPPORT true
#define ULTRASONICS_SUPPORT true
