# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\DroneDeveloper\PycharmProjects\ElectricsEaglesDevelopV1Redevelop\main_gui.ui',
# licensing of 'C:\Users\DroneDeveloper\PycharmProjects\ElectricsEaglesDevelopV1Redevelop\main_gui.ui' applies.
#
# Created: Fri Nov 22 00:06:19 2019
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets
from PySide2.QtWebEngineWidgets import QWebEngineView
from PySide2.QtCore import QUrl


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(672, 600)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setObjectName("comboBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.comboBox_2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_2.setObjectName("comboBox_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pushButton)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.label)
        self.gridLayout_3.addLayout(self.formLayout, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pushButton_2)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_5.setStyleSheet("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.pushButton_5)
        self.gridLayout_4.addLayout(self.formLayout_3, 0, 0, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_2)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_4.addWidget(self.plainTextEdit, 0, 2, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.tab_3)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.gridLayout_5.addWidget(self.plainTextEdit_2, 0, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_5.addWidget(self.pushButton_6, 1, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 2, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_6.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout)
        self.checkBox = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox.setObjectName("checkBox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_2.setObjectName("checkBox_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_3.setObjectName("checkBox_3")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.checkBox_3)
        self.checkBox_5 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_5.setObjectName("checkBox_5")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.checkBox_5)
        self.checkBox_6 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_6.setObjectName("checkBox_6")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.checkBox_6)
        self.checkBox_4 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_4.setObjectName("checkBox_4")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.checkBox_4)
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_7.setObjectName("pushButton_7")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_8.setObjectName("pushButton_8")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.pushButton_8)
        self.gridLayout_9.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.tab_4)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.gridLayout_9.addWidget(self.plainTextEdit_3, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.web_api = QWebEngineView()
        self.web_api.setObjectName("web_api")
        self.gridLayout_7.addWidget(self.web_api, 0, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 672, 26))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout_us = QtWidgets.QAction(MainWindow)
        self.actionAbout_us.setObjectName("actionAbout_us")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuAbout.addAction(self.actionAbout_us)
        self.menuAbout.addAction(self.actionExit)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(
            QtWidgets.QApplication.translate("MainWindow", "ElectricsEagles Development Platform V1.00 ", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Connect", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab),
                                  QtWidgets.QApplication.translate("MainWindow", "Connect Drone", None, -1))
        self.pushButton_4.setText(QtWidgets.QApplication.translate("MainWindow", "Flash Calibrate", None, -1))
        self.pushButton_3.setText(QtWidgets.QApplication.translate("MainWindow", "Flash  Check", None, -1))
        self.pushButton_2.setText(QtWidgets.QApplication.translate("MainWindow", "Flash ZIP", None, -1))
        self.pushButton_5.setText(QtWidgets.QApplication.translate("MainWindow", "Clean crystal", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2),
                                  QtWidgets.QApplication.translate("MainWindow", "Flash Drone", None, -1))
        self.pushButton_6.setText(QtWidgets.QApplication.translate("MainWindow", "Calibrate", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3),
                                  QtWidgets.QApplication.translate("MainWindow", "Calibrate Drone", None, -1))
        self.checkBox.setText(QtWidgets.QApplication.translate("MainWindow", "Debug Mode", None, -1))
        self.checkBox_2.setText(QtWidgets.QApplication.translate("MainWindow", "Manual support mode", None, -1))
        self.checkBox_3.setText(QtWidgets.QApplication.translate("MainWindow", "Manual support logo", None, -1))
        self.checkBox_5.setText(QtWidgets.QApplication.translate("MainWindow", "Buzzer support", None, -1))
        self.checkBox_6.setText(QtWidgets.QApplication.translate("MainWindow", "Ultrasonics support", None, -1))
        self.checkBox_4.setText(QtWidgets.QApplication.translate("MainWindow", "AutoPilot Support", None, -1))
        self.pushButton_7.setText(QtWidgets.QApplication.translate("MainWindow", "Generate Firmware", None, -1))
        self.pushButton_8.setText(QtWidgets.QApplication.translate("MainWindow", "Save Edited", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4),
                                  QtWidgets.QApplication.translate("MainWindow", "Setup Drone", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5),
                                  QtWidgets.QApplication.translate("MainWindow", "API", None, -1))
        self.menuAbout.setTitle(QtWidgets.QApplication.translate("MainWindow", "About ", None, -1))
        self.actionAbout_us.setText(QtWidgets.QApplication.translate("MainWindow", "About us", None, -1))
        self.actionExit.setText(QtWidgets.QApplication.translate("MainWindow", "Exit", None, -1))
